# Generated by Django 2.0.4 on 2018-04-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_auto_20180403_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(null=True, through='communities.CommunityMember', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='communities.Community'),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communities', to='accounts.User'),
        ),
    ]
